version: '3.1'

services:

  mysql:
    image: mysql:8.4.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: cloud_file_storage
    ports:
      - "3306"
    volumes:
      - mysql_vol:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root" ]
      interval: 5s
      timeout: 2s
      retries: 3
    restart: always

  redis:
    image: redis:7.2.4
    container_name: redis
    volumes:
      - redis_vol:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 2s
      retries: 3
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ':9001'
    volumes:
      - minio_vol:/data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: scathies/cloud-file-storage:1.0.0
    ports:
      - "80:80"
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
      minio:
        condition: service_healthy

volumes:
  mysql_vol:
    name: mysql_vol
  redis_vol:
    name: redis_vol
  minio_vol:
    name: minio_vol



