spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_file_storage
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:./db/changelog/db.changelog-master.yml

minio:
  username: admin
  password: password
  endpoint: http:/localhost:9000
  bucket-name: