spring:
  session:
    redis:
      flush-mode: on_save

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  datasource:
    url: jdbc:mysql://localhost:3306/cloud_file_storage
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:./db/changelog/db.changelog-master.yml

file-storage:
  username: admin
  password: password
  endpoint: http:/localhost:9000
  bucket-name: dev-cfs
  root-folder-template: user-%s-files/

server:
  servlet:
    session:
      timeout: 1800
